controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

tipos_consultar:
    path: /vertipos
    controller: App\Controller\TiposController::consultar
